### ISSUE TITLE
Refactor rand from `ff` to its own crate

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/algebra#113]
its a bit odd that `test_rng` and `uniform_rand` traits are coming from `ark-ff` at the moment. This also introduces oddities like #112 now introducing a dev-dependency to `ark-serialize` on `ark-ff`.

Refactoring this into its own crate I think will also give more flexibility for allowing feature flags on the `test_rng` that don't make sense to add when its on `ark-ff`. (E.g. making `test_rng`'s seed non-static if you're trying to run randomized tests on more data points)

**Comment by Pratyush** [comment]
Yeah, I was thinking of moving them to ark-std. how does that sound?

**Comment by ValarDragon** [comment]
That sounds good to me

**Comment by ValarDragon** [comment]
Should rand be its own crate in `arkworks-rs/utils`, or should it just be a single file in `ark-std`?

**Comment by Pratyush** [comment]
just a single file in ark-std, probably a module named `rand`. (Basically, we would just move the `rand` module of `ark-ff` there)

**Comment by ValarDragon** [comment]
Opened a PR to do that on `ark-std`. I think we should then mark the rand methods in `ark-ff` as deprecated (so that things won't break in release v0.2.0), and then delete the methods in `ark-ff` on master after the next release.

**Comment by Pratyush** [comment]
Let's re-export `ark-std`'s rand to avoid this breakage.

**Comment by ValarDragon** [comment]
We can't deprecate a re-export unfortunately (https://github.com/rust-lang/rust/issues/30827)

I propose for now we do the following:

* have ark-ff re-export the `UniformRand` trait with a notice in the changelog that its deprecated and to update your dependency before the next release. This is because `UniformRand` is a trait, and multiple versions will probably cause issues AFAIU.

* Have ark-ff re-implement test_rng(), with a deprecated flag to switch to ark_std. (Which will also remind them to switch for Uniform Rand if they use it)

**Comment by Pratyush** [comment]
Hmm that's unfortunate, but your workaround is good enough, I suppose.
