### ISSUE TITLE
Implement smaller test field for mixed radix

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/algebra#118]
Currently the field we use for mixed radix tests is `MNT6Fr`, whose radix 2 component is relatively large (15 or 16). This forces the mixed radix FFT tests to do a 2**17-sized mixed radix FFT, which is the slowest test in the repository by a large margin.

We should implement a field to test with, that has a much smaller radix-2 component, so we can test the mixed radix FFT on smaller polynomial sizes.

**Comment by weikengchen** [comment]
There is a shortcut---implementing a field that is basically `MNT4Fr`, but we cheat that its radix-2 component is small.

**Comment by Pratyush** [comment]
> There is a shortcut---implementing a field that is basically MNT4Fr, but we cheat that its radix-2 component is small.

Sure, we can put this in `test-curves`

**Comment by weikengchen** [comment]
(Just a correction that I previously said `MNT4Fr`, it is `MNT6Fr`, in case someone is heading in the wrong direction...)

**Comment by weikengchen** [comment]
Given the challenges Nick and I were facing in the PR, I might start to find a curve that has low 2-arity (which I assume would be easy?)

**Comment by Pratyush** [comment]
Hmm just saw the comment on the PR; yeah I think it might be easier to just start with a different mixed-arity curve.

**Comment by Pratyush** [comment]
(It actually just needs to be a prime field, not even a curve, and sampling such field should be easy)
