### ISSUE TITLE
Poly: Investigate Faster sparse polynomial evaluation methods

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/algebra#123]
At the moment, the logic for sparse polynomial evaluation is:
```
let total = self.coeffs.iter()
            .map(|(i, c)| (*c * point.pow(&[*i as u64])))
            .sum();
```

This recomputes the power of point for each term, which is more costly than need be.

Sparse polynomials for the most part used in vanishing polynomials in our codebase. I suggest we write a fast path for sparse polynomial evaluation, when all terms are powers of 2. (This captures vanishing polynomials for unions of cosets, and vanishing polynomials for subspaces of binary fields)
 
Then for general sparse polynomial evaluation, I suggest we compare the current method against computing all of the squares, and then make the per-term work just computing the correct product of the squares. (As this removes any duplicate squarings computed)

_Originally posted by @ValarDragon in https://github.com/arkworks-rs/algebra/pull/117#issuecomment-741568583_

**Comment by jon-chuang** [comment]
well, naively, one solution is just to precompute the powers of 2 of the point, and implement the right addition chain for the given exponent i.

I agree this current method is quite ugly.
