### ISSUE TITLE
From num::BigInt into algebra_core::Fp256<algebra::bls12_381::FrParameters>

### ISSUE THREAD

**Issue by brucechin** [arkworks-rs/algebra#135]
Hello,

If I want to create a Fq instance from some very big integer and I can not use u128. I choose num::BigInt to do it. Here is my code:

`let test : Fq = pow(BigInt::from(2), 200).into();`

The failure is:
> the trait `std::convert::From<num::BigInt>` is not implemented for `algebra_core::Fp256<algebra::bls12_381::FrParameters>`

How could I achieve the same functionality without using the num::BigInt or do you have any plans to implement the trait for BigInt? Thanks!

**Comment by weikengchen** [comment]
There are two hints:

1. To do 2^200, maybe the easiest way to implement is 1<<200, the `muln` function of `BigInt` provides this functionality (https://github.com/arkworks-rs/algebra/blob/master/ff/src/biginteger/mod.rs).

2. To convert a BigInt into a Fp, use Fp::from_repr

**Comment by brucechin** [comment]
for code like 

```
let mut test= BigInteger256::from(1u64);
let hello : Fq = (test.muln(200)).into();
```

similarly, the trait is not implemented for BigInteger256 in the algebra library
> the trait `std::convert::From<()>` is not implemented for `algebra_core::Fp256<algebra::bls12_381::FrParameters>`

**Comment by weikengchen** [comment]
You need to run `test.muln(200)` in a separate line since it modifies `test` and returns `()`. What you need to pass is `muln`.

**Comment by brucechin** [comment]
Thanks! You helped me solve this problem!
