### ISSUE TITLE
serialize tests Dummy is poorly written

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/algebra#152]
By not serializing to the actual type, it fails certain invariants, such as the fact that default impls for methods rely on other methods (such as uncompressed, unchecked). It is of questionable utility.

**Comment by weikengchen** [comment]
I agree that its `serialize_uncompressed` and `serialize_unchecked` should use the `[u8]`'s  `serialize_uncompressed` and `serialize_unchecked`.

Let me do it in an upcoming PR.

**Comment by jon-chuang** [comment]
Actually I noticed my actual issue was something to do with the old `serialized_unchecked` being actually uncompressed. I fixed it in a forthcoming update to https://github.com/arkworks-rs/algebra/pull/130.

I guess morally speaking, what it is doing makes sense
