### ISSUE TITLE
error[E0432]: unresolved import `ark_std::UniformRand`

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/algebra#181]
when building ff with cargo.toml: 
`ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }`

**Comment by ValarDragon** [comment]
I think you may need to `cargo update`? This was introduced a couple of weeks ago to ark-std

**Comment by jon-chuang** [comment]
Yes, this fixed it, my bad
