### ISSUE TITLE
Use improved Final Exponentiation algorithms for BLS12 curves

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/algebra#195]
Yousef recently benchmarked a variety of pairing based curve libraries' performance here: https://hackmd.io/@zkteam/eccbench, which is extremely helpful for identifying places to improve performance!

Something notable is that the difference in final exponentiation speed for a variety of curves is >2x relative to the implementation in `gurvy`.  (The base curve arithmetic is faster in gurvy as well, suggesting that a lot of the speed difference is also attributable to base field speed differences). 

The hard part of the final exponentiation in `gurvy` ([bls12-377 src](https://github.com/ConsenSys/gurvy/blob/develop/bls377/pairing.go#L54), [bls12-381 src](https://github.com/ConsenSys/gurvy/blob/develop/bls381/pairing.go#L73) ) uses improved algorithms from https://eprint.iacr.org/2020/875.pdf, along with ideal addition chains for exponentiating by `t` and `t/2`. That algorithm claims to take ~500 fewer base field multiplications than the prior state of the art.

Arkworks currently implement something slower than the mentioned prior of the state. (Assuming tight implementations of sub-routines, it takes ~5 extra operations in Fp12, which is around 500 base field operations. Furthermore the arkworks implementation has significantly higher register pressure, which is likely a significant performance hit at the relevant field sizes)

I think we should amend the bls12 parameters to include an addition chain for exponentiating by `t` and `t/2` (I confess that I'm not yet clear on what `t` is yet), and implement it.

Its likely that the improved algorithm has different cases that need to be accounted for, as the bls12-381 and bls12-377 final exponentiation code in gurvy are not the same.

**Comment by jon-chuang** [comment]
Thanks @ValarDragon . I think it would be interesting to investigate what changes could be made to the group ops add and double to be more on par with the competing libraries. This probably deserves a different issue.

One wonders whether the limitations exist in how things are inlined or other compiler level things.

Personally, I'd like to bench some of these results myself. I'm unhappy with the sometimes inconsistent results one can get when calling --target=native v.s. not doing so.

**Comment by ValarDragon** [comment]
I took a look at the mixed addition formulae, and they are exactly the same for the short weierstrass curves. This leads me to believe that the speed difference there is between field arithmetic differences, and compiler-level things / inlining.

**Comment by Pratyush** [comment]
The mixed addition and doubling formulae are the same. The only difference I can think of is that the compiler is not optimizing out temporaries well, so we might have to move to using the `_assign` variants, which perform operations in place.

**Comment by jon-chuang** [comment]
I did think of another explanation, which is that the bottleneck is in fact not in the mul and squaring, since when I benched them they were neck and neck or faster than goff or mcl, but rather in addition and subtraction, which use iterators as defined in the biginteger trait

**Comment by jon-chuang** [comment]
So yes, there is a discrepancy between arkworks and celo-org/zexe, for bls12_381, fq square is 34.4ns in former vs 25.0ns in latter. That's a 37.6% difference, which is rather appalling.

**Comment by jon-chuang** [comment]
I can only conclude that the port was done in a rushed manner with little concern for checking correctness, as I have encountered numerous uncalled-for modifications, which must have been the source of all these issues we have encountered recently. This is quite appalling as one expects that in a port, one should be cautious to be as faithful to the original as possible.

**Comment by Pratyush** [comment]
The assembly output is the same for zexe and arkworks, so I'm not sure where the difference would lie?

**Comment by jon-chuang** [comment]
In my opinion, it is ill conceived to have reworked the entire asm mul framework without having bothered to bench to check for regressions

**Comment by Pratyush** [comment]
the framework wasn't reworked; I just moved some components around. Most of the code is identical.

**Comment by burdges** [comment]
Appears https://github.com/ConsenSys/gurvy/pull/29 contains the gurvy changes

**Comment by Pratyush** [comment]
> So yes, there is a discrepancy between arkworks and celo-org/zexe, for bls12_381, fq square is 34.4ns in former vs 25.0ns in latter. That's a 37.6% difference, which is rather appalling.

In the last version of `zexe`, the cost of square is still 37ns/iter (same as multiplication), so I think any change in the performance happened before the transition.

**Comment by jon-chuang** [comment]
I think you got it wrong, as it ought to be correct that the mul and square are approximately equal. However, currently on arkworks, the square is about 20% slower (34.5ns vs 28ns). So the regressions according to what you said, seem to have happened after the transition.

**Comment by Pratyush** [comment]
How fast is multiplication? On my machine multiplication and square are both 37 ns/iter

**Comment by jon-chuang** [comment]
Ok, so actually I didn't do `cargo update` to get the asm fix, it appears once I did that, the timings were as expected. I think now that git pull is not enough, I have to remember to do cargo update frequently too.

There seems to have been some improvements against old zexe in terms of fq::add_assign, strangely enough, and also the overall perf of non-asm mul_assign. 

In any case, I estimate the following:
bls12_381::
g1::add_assign_mixed 544ns (v.s. gurvy 387ns).
g1::double 320ns (v.s. gurvy 245ns)

I think if one would like to close such a gap (around 30-40%), one should either write more assembly or unroll loops for most of the operations (add/sub/double/negate). 

The naive impls of these I believe actually have significant contributions to slowdown.

**Comment by mmagician** [comment]
I think this can be closed, since the optimisation as per issue title was done in https://github.com/arkworks-rs/algebra/pull/211.
The discussion around general benchmarking and performance comparisons can be continued in https://github.com/arkworks-rs/algebra/issues/80 if needed, though we should probably define smaller and more concrete optimisation targets if someone's to actually push it forward.
