### ISSUE TITLE
Precompute `2.inverse()` in `Fq2::sqrt`

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/algebra#210]
Right now in `QuadExtension::sqrt`, we compute `2.inverse()`, where `2` is in the basefield. An inverse in `bls12_381::Fq` is ~10,000ns, while `Fq2::sqrt` is 75,000ns, so this is quite a significant cost.

**Comment by Pratyush** [comment]
Maybe one "easy" way would be to make a `const` version of `inverse`, and use that to precompute the constant at compile time.

**Comment by jon-chuang** [comment]
Unfortunately, it's hard to define const ops over slices at the moment.

**Comment by jon-chuang** [comment]
It might however, be possible to do so utilising the framework of const generics. Will investigate.

**Comment by jon-chuang** [comment]
There is actually an easier way to compute any number div 2 than multiplying by 1/2. In montgomery form, one does a div2 on the bigint rep, then conditionally add 1/2 depending on whether the lowest bit had been 1.

**Comment by Pratyush** [comment]
> then conditionally add a montgomery rep 1/2

Wouldn't we have to compute `2.inverse()` anyway?

**Comment by jon-chuang** [comment]
Yes, but this is an orthogonal "optimisation" of the actual multiplication.

**Comment by Pratyush** [comment]
Wait, isn't `2.inverse() == p+1/2`, and we can calculate `p+1/2` easily, as p is odd, so `p+1` is even, and so `p+1/2` is just a `div2()`. So basically we compute `add_no_carry` on the modulus, and use that?

**Comment by jon-chuang** [comment]
Well yes. That's great 🥳

**Comment by jon-chuang** [comment]
I think one nice thing about making biginteger a const generic struct rather than a trait is that one should be able to define as many const fns as one would like, without having to wait for this feature to become stabilised on rustc

**Comment by Pratyush** [comment]
That's true, but the downside is that unrolling the `add_nocarry` and sub_noborrow` loops would again be a pain >.<
