### ISSUE TITLE
Issue with ff for limbs = 1

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/algebra#231]
The following dubious piece of code exists
```
if $limbs == 1 {
    *self = *self * *self;
    return self;
}
```

Could someone explain why this is correct? This looks mighty wrong to me...

If it is correct, please at least add some comments to explain why. Thanks.

**Comment by ValarDragon** [comment]
Can you link to the relevant lines of source code?

**Comment by jon-chuang** [comment]
My bad, it's here https://github.com/arkworks-rs/algebra/blob/91bb87b512cbaa68c76d9584bb8bd4810267840c/ff/src/fields/arithmetic.rs#L84

**Comment by weikengchen** [comment]
It seems fine, as follows.

Note, it is not multiplying the 64-bit limb with itself, which would likely cause an overflow. Instead, it just not uses any special trick for squaring, but delegates to the multiplication of a field element by itself, which is done by another macro.

**Comment by jon-chuang** [comment]
Oh you're absolutely right. I should add a comment to clear up the confusion.
