### ISSUE TITLE
Adopt standard software management practices i.e. dependency versioning

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/algebra#238]
It is fairly weird that we are utilising master as the version for downstream dependencies. Perhaps the rationale is that we are not at a release stage of the project yet. Still, it seems wise to start maintaining branches of release versions and in addition to a breakage-prone master? Especially since arkworks is actually being deployed.

**Comment by ValarDragon** [comment]
We're actually working on getting releases out for all the crates right now haha. We ideally should have everything in place to make a release in a couple days

**Comment by jon-chuang** [comment]
Ooh awesome!

**Comment by weikengchen** [comment]
Basically, or ideally, these repos would be on crates.io, and people no longer point to GitHub.

**Comment by Pratyush** [comment]
Right, the main blocker is https://github.com/arkworks-rs/utils/pull/29, and the corresponding downstream PRs

**Comment by ValarDragon** [comment]
Releases are out! Closing this for now, please open new issues if theres any other software development practice's you'd recommend
