### ISSUE TITLE
Remove duplicate code for tests

### ISSUE THREAD

**Issue by mmaker** [arkworks-rs/algebra#256]
The code used within `test-templates/` is copy-pasted a lot of times across the codebase (especially in arkworks-rs/algebra and arkworks-rs/curves): see e.g.  #241, https://github.com/arkworks-rs/curves/blob/master/mnt4_298/src/curves/tests.rs and https://github.com/arkworks-rs/algebra/blob/master/test-curves/src/bls12_381/tests.rs .
Additionally, multi-scalar multiplication is not being tested currently. 

It would be awesome if someone could improve on #241 and create generic macros to test for groups, for instance with a macro like:

```rust
macro_rules! generate_g1_test {
    ($i: ident) => {
        #[test]
        fn test_g1() {
            curve_tests::<$crate::$i::g1::G1Projective>();
            sw_tests::<$crate::$i::g1::Parameters>();
            group_tests::<$crate::$i::g1::G1Projective>();
            test_var_base_msm::<$crate::$i::g1::G1Affine>();
        }
    }
 }
```
that is called e.g. as ` generate_g1_test!(bn384_small_two_adicity);`. It'd greately improve the test suite while removing a lot of useless lines of code!

**Comment by huyuncong** [comment]
Also, see pull request 90 in the curves library. 
I think all the problems are addressed, and this issue can be closed.
