### ISSUE TITLE
Easier conversion for scalars from a smaller sized field to a larger scalar field

### ISSUE THREAD

**Issue by alxiong** [arkworks-rs/algebra#271]
It should be a common task to add smaller scalar (e.g. Jubjub scalar) to a circuit over a larger scalar field (e.g. BLS), and right now there's no clear API from the library that support such conversion.

The only hacky way I find is through their commonly shared `BigInteger` trait, thus one may do the following as of `v0.2.0`:

```rust
use ark_bls12_381::Fr as BlsScalar;
use ark_ed_on_bls12_381::Fr as JubjubScalar;
use ark_ff::{BigInteger, PrimeField};

let s = JubjubScalar::rand(&mut rng);
let s_in_bls = BlsScalar::from_le_bytes_mod_order(&s.into_repr().to_bytes_le()); // THIS LOOK UGLY
```

Hopefully there's some `impl<P: FrParameters> TryFrom<FpXXX<P>> for FpXXX<P>` which compares the `MODULUS` and if dest scalar is larger, then does the conversion?
Or maybe there're some better ways to do it?

**Comment by burdges** [comment]
Why would this be common?  Just ECDSA?  See also https://github.com/arkworks-rs/nonnative

**Comment by weikengchen** [comment]
I think Alex is thinking about a version of nonnative field, but not in the R1CS, rather, in the Rust ecosystem.

The hacky way that you pointed out is also the only way I know: convert it into bytes and take it back.

**Comment by alxiong** [comment]
> I think Alex is thinking about a version of nonnative field, but not in the R1CS,

yes, that's right.

> Why would this be common?

curve operation inside circuit is an example. I think it's a common practice to use a curve (Jubjub) over a base field that's the same size as another scalar fields (Bls) to reduce the total number of constraints required for operations like scalar multiplication, point addition etc. 

> The hacky way that you pointed out is also the only way I know

I'm not 100% sure that hacky way is correct tho, it definitely compiles, but I don't know whether the `xxx_mod_order()` part would skew the value.

**Comment by weikengchen** [comment]
Let me summary the issue, and let me suggest one change to the repo...

I worked with Alex offline. I think we find one thing:

If one does this to a prime field element s,

`println!("the value of a field element: {}", s)`, this would output the correct value (via the Display trait implementation).

`println!("the value of a field element: {:?}", s)`, this would output the Montgomery representation (via the Debug trait implementation).

It might be confusing. Should we make them the same? 

This is in contrast to BigInteger's Debug and Display, where they will show the same value, just in different formats (one hex, one dec).

@ValarDragon @Pratyush

**Comment by ValarDragon** [comment]
err, I don't understand the last comment relative to the first one.

But for printing the prime field element, I feel like we should always print the correct value. The montgomery representation is only helpful for you when you're working on the field arithmetic itself, in which case I think its fine to get the underlying bigint to print.

**Comment by weikengchen** [comment]
I was referring to that PrimeField behaves differently compared with BigInteger, as the latter always outputs the real value regardless of `Debug` (aka `{:?}`) or `Display` (aka `{}`)

**Comment by ValarDragon** [comment]
ah sorry, I meant the println issue vs the original post. Is the use case from the original post not needed anymore?

**Comment by weikengchen** [comment]
Got what you mean. Yes, the problem in the original post is solved (indeed, the numbers are "different" because Alex prints out the Montgomery representations).

**Comment by weikengchen** [comment]
(Maybe let me close this issue also)

**Comment by alxiong** [comment]
@ValarDragon , allow me to give my account of the issue.

The "hacky way" I found in the original post does work as intended, and at first I thought it doesn't since I print out its Debug format, thus the Montgomery repr that appears to be different after conversion. In actual fact, @weikengchen helped me realized that the conversion is correct since the actual value before and after the conversion is the same (what Display prints out, or `scalar.into_repr()` are the same)

With that said, I still don't think this "hacky way" is a clean API, and I hope there would be some refactoring job to be done to offer an easier conversion API.

That's my take, feel free to re-open this issue at your (or the team's) discretion

**Comment by weikengchen** [comment]
Let me re-open this issue. Yes, another problem that is indeed not solved is that it is not very easy to convert between different fields. 

I think the main question is about should we allow this? (since it is essentially two different finite primes?)

Consider using Jubjub inside another circuit (e.g., for Pedersen), in R1CS, when one wants to multiply a group element, currently the R1CS gadgets ask you to use bits.

**Comment by daira** [comment]
Conversion between fields is useful and sometimes necessary. For example in Zcash Orchard we sometimes need to convert between the base and scalar fields of Pallas.

**Comment by weikengchen** [comment]
Yes, I agree.
