### ISSUE TITLE
[poly] Paralleled Mul with feature flag "parellel" 

### ISSUE THREAD

**Issue by alxiong** [arkworks-rs/algebra#272]
Now with feature flag `parallel`, the multiplication of two polynomials is indeed using a concurrent impl, however, for a polynomial to multiply by a field element, the implementation is not, i.e. the [`impl Mul for DensePolynomial` here](https://github.com/arkworks-rs/algebra/blob/master/poly/src/polynomial/univariate/dense.rs#L401-L416)

Would be great if the team can add a layer of indirection similarly using `internal_mul()` which conditionally compiled a rayon-accelerated version if the "parallel" feature flag is on. This should be a small and quick change.

Thanks!

**Comment by weikengchen** [comment]
This seems not as expected... as you can see,  the impl Mul<F> uses `cfg_iter_mut`, and the implementation of `cfg_iter_mut` uses parallel:

```
#[macro_export]
macro_rules! cfg_iter_mut {
    ($e: expr, $min_len: expr) => {{
        #[cfg(feature = "parallel")]
        let result = $e.par_iter_mut().with_min_len($min_len);

        #[cfg(not(feature = "parallel"))]
        let result = $e.iter_mut();

        result
    }};
    ($e: expr) => {{
        #[cfg(feature = "parallel")]
        let result = $e.par_iter_mut();

        #[cfg(not(feature = "parallel"))]
        let result = $e.iter_mut();

        result
    }};
}
```

**Comment by alxiong** [comment]
Oh, I see! Thanks for the clarification. Sorry for the noise.
