### ISSUE TITLE
Potential issue of implementing Into<BigUint> and From<BigUint> for BigInteger (and for PrimeField)

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/algebra#282]
In #280, the PR plans to add the implementation of From and Into BigUint for BigInteger, as well as something similar for PrimeField. The goal is to allow easy conversions between different fields. Also, making it into BigUint helps to debug and to do some operations that are not in a prime field.

A problem shows up recently when testing an old program using this in-progress branch. 

Because PrimeField has several "From<>" and "Into<>", adding more "Into<>" and "From<>" may confuse the compiler. For example, PrimeField can be "into" [u64]. Previously it suffices to just use "into()". Now the compiler may be confused about whether to convert it into [u64] or BigUint, and the compiler will now request an explicit type notation. (Though Rust is smart, sometimes Rust is not smart enough and would not try hard enough to figure out the types.)

That is, the additional From<> and Into<> may break existing code.

### Proposed solution

I would propose making the conversion from and into BigUint not use From and Into. Instead, there would be a special function like from_biguint() and to_biguint(), which mimics that TryFrom/From/Into.

This would avoid affecting existing code that uses `into` to get [u64].

cc @Pratyush for more feedback.

**Comment by weikengchen** [comment]
also cc @daira for some feedback.

**Comment by Pratyush** [comment]
Code breakage due to type inference changes is not usually considered a
breaking change

**Comment by alxiong** [comment]
what do you think of using feature flag to circumvent the issue? namely:

```rust
#[cfg(feature = "bigint_conv")]
impl From<BigInteger> for PrimeField { ... }
```
which makes the downstream library who wants to use this new overloaded From<>, conscientious about the possible breaking changes (by enabling the feature flag) and add explicit type declaration on their existing code.

and this won't break existing code, since this flag is disabled by default.

**Comment by weikengchen** [comment]
The feature flag would not work nicely because it would likely many dependent repos to also use this flag, otherwise there would be a mismatch.

I am still a little bit concern about code breakage due to type inference since it is still breaking somehow? And I would try to minimize the users' cost.

**Comment by daira** [comment]
I have no particular preference other than consistency. I.e. either use the `to/from_typename` approach consistently, or use multiple From/Into implementations consistently.

I view Arkworks as being at a point in its lifetime where APIs are still in flux, so I wouldn't mind updating code on a version bump. You should ask users who have deployed it in production, though.

**Comment by Pratyush** [comment]
Personally I think that since we'll be bundling this into a list of breaking changes anyway, it's fine to break inference stability, and in particular let's keep the `From` and `Into` impls.

**Comment by weikengchen** [comment]
No problem. Let me move the PR back to the previous version.

**Comment by Pratyush** [comment]
Thanks!
