### ISSUE TITLE
Implement Sum trait for Group elements

### ISSUE THREAD

**Issue by ggkitsas** [arkworks-rs/algebra#288]

**Comment by weikengchen** [comment]
Ideally, it should have been already there: https://github.com/arkworks-rs/algebra/blob/master/ec/src/group.rs#L39

(untested)

**Comment by weikengchen** [comment]
Oh wait I know: GroupAffine by default does not implement the `Group` trait and does not have "sum". 

Because GroupAffine cannot nicely represent "zero", which can happen when:
- summing an empty vector
- summing aG and -aG (e.g., part of the natural computation)

But G1Projective should have it.

**Comment by weikengchen** [comment]
Thinking about that further, it seems also possible to add a Sum implementation to GroupAffine.

But I want to caution that the computation might be faster if all are done on projective curves (avoid some back-and-forth conversions).

**Comment by weikengchen** [comment]
Maybe the performance is a strong motivation toward adding a Sum trait.

The Sum trait can make sure that it adds a bunch of points together (over projective curves) and then does only one conversion back to the affine curve, which can avoid many unnecessary inversions over the field.
