### ISSUE TITLE
Migrate away from `llvm_asm` to `asm`

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/algebra#305]
`llvm_asm` is being deprecated: https://github.com/rust-lang/rust/pull/87590

**Comment by weikengchen** [comment]
We need to boost the urgency of this. As it appears that the latest version of Rust stable has deprecated it.

**Comment by weikengchen** [comment]
> @weikengchen This is the issue I mentioned during our meeting.
> 
> Using the latest release of this repository 0.3.0 and using the nightly channel of Rust.
> 
> I tried building the release locally as well as letting cargo take care of the package.
> 
> Here is the dump output: [dump.txt](https://github.com/arkworks-rs/algebra/files/8006072/dump.txt)
> 
> edit: Note this dump was generated from attempting to run Gemini's docs.

Got it. I think this is expected, as the nightly officially bans the llvm_asm. The stable version of Rust should be fine.

There is still one remaining fix necessary for the #306. I will watch closely.

**Comment by s7117** [comment]
> Got it. I think this is expected, as the nightly officially bans the llvm_asm. The stable version of Rust should be fine.
> 
> There is still one remaining fix necessary for the #306. I will watch closely.

Thanks. I was using nightly as rust complains about using in Gemini `#![feature]` on the stable release channel.
[stable_dump.txt](https://github.com/arkworks-rs/algebra/files/8006555/stable_dump.txt)

**Comment by weikengchen** [comment]
> > Got it. I think this is expected, as the nightly officially bans the llvm_asm. The stable version of Rust should be fine.
> > There is still one remaining fix necessary for the #306. I will watch closely.
> 
> Thanks. I was using nightly as rust complains about using in Gemini `#![feature]` on the stable release channel. [stable_dump.txt](https://github.com/arkworks-rs/algebra/files/8006555/stable_dump.txt)

This seems to be a Gemini issue now, so we will discuss somewhere else. 

The fix is probably this: use nightly, and change the Cargo.toml of Gemini to remove "asm" from its default feature list.

https://github.com/arkworks-rs/gemini/blob/main/Cargo.toml#L91
