### ISSUE TITLE
CI Breakage on num-bigint 0.4.0

### ISSUE THREAD

**Issue by kevaundray** [arkworks-rs/algebra#316]
### **Problem**

 int_roundings has now been feature gated as an unstable feature, and is now a breaking change on recent nightly builds. 

Tracking issue: https://github.com/rust-lang/rust/issues/88581

In the issue, they note that num-bigint version 0.4.0 has this problem, which is the version that arkworks is using in ark-ff ( and possibly in other crates).

### **Quick fix**:

The simplest fix is to locally run `cargo update -p num-bigint` to update the num-bigint dependency in your lockfile or `cargo update` to update all dependencies including num-bigint.

### **Solution**:

Since num-bigint 0.3.3 or 0.4.2 has this fix applied, a solution would be to update to 0.4.2.

### **Reasons to not apply solution**:

- This is not breaking for stable, so may not be a priority since there is a quick fix.
- It is not clear to me that discussions around function naming have been resolved, so eagerly updating may require you to update again if the function names do change.

For the second point, it is possible to fix the version to 0.4.2 to stop the CI breaking on the now unstable feature and then update again at a later date, if the names do change.

**Comment by weikengchen** [comment]
I think at least it is certain that we need to bump up the version of `num-bigint`. If this bug starts to cause issues for downstream applications, then we need to cut a new release. 

I will make a PR to update the existing repos. The `num-bigint` has been used in a few places.

**Comment by weikengchen** [comment]
Hi Kevaundray, I made a recent PR which is just merged. On my side, it seems to be solve the problem in `ark-algebra` itself. (And it seems that Rust is able to catch the latest version). 

Are you using `ark-ff` as a dependency of another project which has a `Cargo.lock`? In that situation, I feel that `cargo update` seems necessary.

**Comment by kevaundray** [comment]
> Hi Kevaundray, I made a recent PR which is just merged. On my side, it seems to be solve the problem in `ark-algebra` itself. (And it seems that Rust is able to catch the latest version).
> 
> Are you using `ark-ff` as a dependency of another project which has a `Cargo.lock`? In that situation, I feel that `cargo update` seems necessary.

Hey Weikeng,

Yep I agree,  `cargo update` is the only solution for already deployed applications due to `Cargo.lock`.

Thanks :) Will close this issue as the PR is merged!
