### ISSUE TITLE
How can I write a circuit for random number generation?

### ISSUE THREAD

**Issue by brucechin** [arkworks-rs/algebra#323]
I am curious that if I want to sample a random integer number from a Gaussian distribution, how can I represent such a program using circuit? Thanks!

**Comment by weikengchen** [comment]
Since the circuit is technically verifying things instead of proving, so let me ask a question back: what do you want to prove?

**Comment by brucechin** [comment]
Suppose y = f(x, w), x is public input, w is secret input from the prover, now I want to prove y' = f(x, w) + r, where r is a random number sampled from Gaussian(\miu, \delta^2). Intuitively I think this randomness can not be verified? :(

**Comment by weikengchen** [comment]
To add to the closure, we discussed offline. And believe that one can either prove that the prover's noise is within a reasonable bound, or use Poseidon + New Hope's approximation to prove that the prover use random numbers honestly.
