### ISSUE TITLE
Why are we maintaining our own version of unroll?

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/algebra#33]
Yes, the crate dev is not responsive, but are there really necessary changes?

**Comment by Pratyush** [comment]
The version on crates.io has an old version of `syn` and `quote`, both of which have sizable contributions to compile time. I've submitted a PR to the repo, but it has stagnated for a few months now.

Also, I would prefer to avoid a relatively unmaintained third party dependency in a critical part of the code

**Comment by jon-chuang** [comment]
I see, thanks
