### ISSUE TITLE
[ark-ec] `UniformRand` trait bound for `AffineCurve` missing

### ISSUE THREAD

**Issue by CPerezz** [arkworks-rs/algebra#331]
While using today `ark-ec` I stumbled across this thing where I tried to generate a random `G1Affine` but the only way seems to generate a random `G1Projective` and turn it into affine.

Is there any specific reason why `+ UniformRand` is not added in the `AffineCurve` trait bounds?
I understand that you need to operate with the points to generate a random one, and therefore at some point you need to use Projective Coordinates. But from an API perspective I don't see a reason to not to have a simple call to the `ProjectiveCurve` trait API and do the conversion internally so that the trait bound is already implemented.

I can file a PR with it! :) Unless there's a reason why this is not done.

Thanks a lot for this amazing library BTW!!!! :smile:

**Comment by Pratyush** [comment]
You're right, it's unnecessarily missing. A PR would be appreciated!
