### ISSUE TITLE
[ark-poly] Add field internal getters for `EvaluationDomain` trait

### ISSUE THREAD

**Issue by CPerezz** [arkworks-rs/algebra#332]
Currently, if you want to use a `GeneralEvaluationDomain` so that you can be more generic and have the implementation falling back in the `MixedRadixEvaluationDomain`, it turns a bit more difficult to access the fields of the domain itself.

So for example. It would be nice that you could call `domain.group_inv()` or `domain.domain_size_log()` as you do now with `domain.size()`.

Considering that all three `GeneralEvaluationDomain`, `MixedRadixEvaluationDomain` and `Radix2EvaluationDomain` all implement `EvaluationDomain` trait, wouldn't make sense to add there the extra methods to gain access to the fields directly? Or at least add them for `GeneralEvaluationDomain`.

Since otherways we need to do hacks like:
```rust
pub fn get_domain_attrs<F: FftField>(
    domain: &GeneralEvaluationDomain<F>,
    attr: &'static str,
) -> F {
    match domain {
        GeneralEvaluationDomain::MixedRadix(domain) => match attr {
            "group_gen" => domain.group_gen,
            "group_gen_inv" => domain.group_gen_inv,
            "generator_inv" => domain.generator_inv,
            "size_as_fe" => domain.size_as_field_element,
            "size_inv" => domain.size_inv,
            _ => unreachable!(),
        },
        GeneralEvaluationDomain::Radix2(domain) => match attr {
            "group_gen" => domain.group_gen,
            "group_gen_inv" => domain.group_gen_inv,
            "generator_inv" => domain.generator_inv,
            "size_as_fe" => domain.size_as_field_element,
            "size_inv" => domain.size_inv,
            _ => unreachable!(),
        },
        _ => unreachable!(),
    }
}
```

I would like to do a PR for that as I think it would not break the API if we don't touch the trait and we just add some similar hack inside the `GeneralEvaluationDomain` enum.

Any ideas/concerns?

**Comment by Pratyush** [comment]
That's a good idea! Let's add the methods directly to the `EvaluationDomain`. It would be a breaking change, but that's okay as I think the only implementors of the trait are in this crate anyway.

**Comment by CPerezz** [comment]
Will try to do a PR ASAP! 😊😊
