### ISSUE TITLE
Square root method for quadratic fields does not cover the case when p = 3 mod 4

### ISSUE THREAD

**Issue by kevaundray** [arkworks-rs/algebra#344]
## Problem 

Given that the method to compute the square root in a quadratic field is here: https://github.com/arkworks-rs/algebra/blob/master/ff/src/fields/models/quadratic_extension.rs#L349

 It seems to only cover the case when p = 1 mod 4 and not when p = 3 mod 4.

## Failing test

This would be a problem for all Fp2 parameters with the following line:
 
```rust
const NONRESIDUE: Fq = field_new!(Fq, "-1");
```

Taking bls12-381 as an example, the following test fails but should pass:

```rust
fn test_splitting_field() {
        use ark_bls12_381::{Fq, Fq2};
        use ark_ff::{One, PrimeField, SquareRootField, Zero};

        let fq = -Fq::one();
        assert!(fq.sqrt().is_none()); // should be a non residue, since p = 3 mod 4

        let fq2 = Fq2::new(-Fq::one(), Fq::zero());
        assert!(fq2.sqrt().is_some()); // should be a residue, expect c0 = 0, c1 = -1
    }
```

## Possible solution

The linked paper  gives two algorithms for the cases p = 3 mod 4 and p = 1 mod 4.

- If p = 1 mod 4, then we can use (Algorithm 8, page15)
- If p = 3 mod 4, then we can use (Algorithm 9, page17)

paper: https://eprint.iacr.org/2012/685.pdf

**Comment by drskalman** [comment]
@mmagician and I looked into algorithm 8 and the problem seems to be that algoritm 8 assumes that if a_1 == 0 then sqrt_q(a_0) exists (in F_q) which is not always true. one can fix the algorithm by simply returning 0+sqrt_q(a_0/beta)*y  when a_0 is a non-residue in F_q.
