### ISSUE TITLE
Make constructors `const`

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/algebra#388]
Right now, when a struct has a trait bound (e.g. `struct QuadExtField<P: QuadExtConfig>`, we cannot make inherent impl methods `const` due to the trait bound. Once https://github.com/rust-lang/rust/pull/93827 lands, we should change as many methods as possible to be const. When this is done for the `new` constructors, this can help us get rid of the `QuadExt` and `CubicExt` macros that were added in #379.

**Comment by mmagician** [comment]
Closed in https://github.com/arkworks-rs/algebra/pull/437
