### ISSUE TITLE
How to use is_identity function?

### ISSUE THREAD

**Issue by etairi** [arkworks-rs/algebra#395]
I want to use the `is_identity` function to check if the `G1Affine` value is an identity element, but the code below throws error saying that the method is not found in `<E as PairingEngine>::G1Affine`. Is there a way to use `is_identity` irrespective of how he `PairingEngine` is instantiated later?
 
```rust
use ark_ec::{PairingEngine, ProjectiveCurve};
use subtle::Choice;

pub struct Signature<E: PairingEngine> {
    pub sigma_1: E::G1Affine,
    pub sigma_2: E::G1Affine,
}

impl<E: PairingEngine> Signature<E> {
     pub fn is_valid(&self) -> Choice {
          self.sigma_1.is_identity()
     }
}
```

**Comment by Pratyush** [comment]
Hey, we don't have an `is_identity` function; you can call `is_zero()`, as the zero element is the identity in additive elliptic curve groups
