### ISSUE TITLE
Unify `SqrtField` and `Field` traits

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/algebra#42]
There's no reason for these traits to be separate; every finite field has square roots.

**Comment by ValarDragon** [comment]
The missing thing at the moment is an efficient sqrt algorithm for cubic extensions AFAIK

**Comment by Pratyush** [comment]
This paper describes how to compute square roots in any field: https://luca-giuzzi.unibs.it/corsi/Support/papers-cryptography/10.1.1.59.4255.pdf

**Comment by Pratyush** [comment]
Done with #422
