### ISSUE TITLE
Residual is_zero for group elements

### ISSUE THREAD

**Issue by weikengchen** [arkworks-rs/algebra#464]
@Pratyush There is a remaining question about is_zero.

In the recent refactoring, it seems that we replace is_zero to is_identity for the group elements.

However, for pairing-friendly cycles, we still use is_zero:

https://github.com/arkworks-rs/algebra/blob/fc7dc3e2a226eade8cda02f6eb2305bdd90b1da8/ec/src/models/bls12/mod.rs#L111
https://github.com/arkworks-rs/algebra/blob/fc7dc3e2a226eade8cda02f6eb2305bdd90b1da8/ec/src/models/bn/mod.rs#L112
https://github.com/arkworks-rs/algebra/blob/fc7dc3e2a226eade8cda02f6eb2305bdd90b1da8/ec/src/models/bn/g1.rs#L44
https://github.com/arkworks-rs/algebra/blob/fc7dc3e2a226eade8cda02f6eb2305bdd90b1da8/ec/src/models/bw6/g1.rs#L45
https://github.com/arkworks-rs/algebra/blob/fc7dc3e2a226eade8cda02f6eb2305bdd90b1da8/ec/src/models/bw6/mod.rs#L234
https://github.com/arkworks-rs/algebra/blob/8eb4e7a50bc4ad1d3f2724b38e6d5958d03c61df/test-templates/src/groups.rs#L270

Do we plan to keep that, or remove that? I can push a PR.

**Comment by Pratyush** [comment]
We changed `is_zero` to `is_identity` for `Affine` elements; for elements of type `CurveGroup`, it's still `is_zero`. Should I can change the `Affine::is_identity` back to `is_zero`?

**Comment by weikengchen** [comment]
I feel for "CurveGroup" we can also do so. The only issue is that it affects many places, right?

**Comment by weikengchen** [comment]
I think it depends on the preference of `is_zero` and `is_identity`, i.e., the reasons for that.

**Comment by burdges** [comment]
fwiw `is_zero` has fewer spurious interpretations.

**Comment by weikengchen** [comment]
Jeff, you mean that `identity` is sometimes also "1" when we talk about a multiplicative group, right?

**Comment by weikengchen** [comment]
@Pratyush I feel maybe we should just revert.

**Comment by Pratyush** [comment]
Okay, making a PR now.
