### ISSUE TITLE
Missing `Pairing::BaseField`?

### ISSUE THREAD

**Issue by mmagician** [arkworks-rs/algebra#502]
In https://github.com/arkworks-rs/algebra/pull/447/ the associated type of `Pairing::Fr` was replaced by `Pairing::ScalarField`.
`Pairing::Fq` was removed without a counterpart added (`BaseField`?). 

Example where this would be needed: https://github.com/arkworks-rs/poly-commit/blob/master/src/kzg10/data_structures.rs#L349

I've got a (somewhat ugly) workaround in this WIP for refactoring poly-commit: https://github.com/arkworks-rs/poly-commit/pull/106/commits/537e307ad25cd5c1849e7ada6a446e3053dc5eff

Should we add `BaseField` to the `Pairing` trait? Is there a better way to do this?

**Comment by Pratyush** [comment]
This is a good catch. Yes, let's do it.
