### ISSUE TITLE
mul_by_te_cofactor

### ISSUE THREAD

**Issue by burdges** [arkworks-rs/algebra#523]
We typically prove group membership when deserializing short Weierstrass curves, but deserialize into the pure curve when handling twisted Edwards curves, and then use explicit cofactor multiplications, but this makes it hard to write code that's polymorphic over curve models.  Should we have a `mul_by_te_cofactor` method, which does nothing for short Weierstrass curves, and multiplies by the cofactor for twisted Edwards curves?

**Comment by Pratyush** [comment]
Not sure I fully understand the issue. Is the idea to (1) premultiply by the cofactor inverse when serializing, (2) deserialize into an Edwards curve point *without* any subgroup checks, and then finally (3) multiply by cofactor to clear any low-order contributions?

**Comment by Pratyush** [comment]
That seems tricky; in particular, we would need to know when the input needs a subgroup check vs. when it needs a cofactor clearing. 

The solution I'd recommend is a custom impl of `CanonicalSerialize/CanonicalDeserialize` for your top-level structs (`Proof`, `VerifyingKey`, etc.). Within those impls, you can implement whatever validation logic you'd like.

**Comment by burdges** [comment]
Alright I'll close this issue for now, but I'm not sure the cofactor clearing style can be represented in deserialization, given this is not how those protocols are typically presented.

**Comment by burdges** [comment]
Agreed it's tricky..

We'd only gain polymorphism from `mul_by_te_cofactor` if we added TE validation criteria in deserialization too.  

At minimum, this creates an aesthetic mess since this validation criteria makes little sense for higher level structs.

At present arkworks has [strong](https://github.com/arkworks-rs/algebra/blob/master/ec/src/models/twisted_edwards/affine.rs#L321) validity criteria for TE curves that agree with validity criteria for SW curves.  If you want a classically weak TE validity criteria then you must do the on curve check manually.

It's clear validation criteria make less sense for higher level objects, like some subprotocol could involve two curves, either of which could be SW or TE.  If otoh we could detect if an `C: AffineCurve` is TE or SW then we could write polymorphic code that pulled this trick correctly.
