### ISSUE TITLE
Allow to overwrite the default implementations of `multi_miller_loop`, `final_exponentiation` and `msm`

### ISSUE THREAD

**Issue by achimcc** [arkworks-rs/algebra#537]
Allow to overwrite the default implementations of `multi_miller_loop`, `final_exponentiation` in the models `bls12` and `BW6` and of the `bigint_msm` function.

We already implemented the required changes in the PR's https://github.com/arkworks-rs/algebra/pull/528, https://github.com/arkworks-rs/algebra/pull/534 and https://github.com/arkworks-rs/algebra/pull/542. Now also #567. The PR #571 is another follow-up related to this issue, which allows us to avoid point preparation in the WASM runtime. 

The reasons for this is that those operations are slow in WebAssembly. It would be very useful for us if we could overwrite the default implementations by host function calls when using Arkworks in a WebAssembly runtime. Other use cases would be to e.g. pass these computations to specialised hardware (FPGA's).

While these PR's are slightly complicating the trait hierarchy, they are not introducing any breaking changes. They just add the option to overwrite the default implementations of those functions if required.

**Comment by achimcc** [comment]
Glad to see that #534 is already merged!

I improved the structure of #528 a bit, now we can overwrite `msm` instead of `bigint_msm`. It should be effectively the same optimization but we don't need the superficial hook any longer?

**Comment by achimcc** [comment]
I added another PR where I applied the analogous changes that were already accepted for `bls12` in #534 also to the `BW6` model: https://github.com/arkworks-rs/algebra/pull/542

**Comment by mmagician** [comment]
Just for the sake of consistency, how about adding it to the rest of the models too?
@weikengchen @Pratyush

I was also thinking of yet another way to achieve this, and while I haven't found one that is re-usable across models, adding an extra trait `BlsPairingParams` to the model and moving the final exp + miller loop there (instead of to `BlsParameters`) I think makes the abstraction cleaner. The currently merged solution isn't very clean and I'm equally not convinced about what I'm proposing, but maybe some of you have a stronger preference towards one or the other.

The downside is that it requires a change, albeit minimal, to the curve implementations themselves. Same for other models, replace `Bls` above with `BW6` etc.

Example here: https://github.com/arkworks-rs/algebra/commit/b5c273c91b87f3fc30d378f513bf561f3a3d155c

**Comment by burdges** [comment]
It's good we merged the  msm parts https://github.com/arkworks-rs/algebra/pull/528 and https://github.com/arkworks-rs/algebra/pull/567 for several reasons, like other options not really existing and regular scalar multiplication being defined in the same place.

I'm mildly worried the pairing components https://github.com/arkworks-rs/algebra/pull/534 and https://github.com/arkworks-rs/algebra/pull/542 complicate the traits without achieving much however, so maybe they warrant slightly more discussion.

**Comment by achimcc** [comment]
It would be awesome if we could serialize the arguments of `multi_miller_loop` without preparing them first in WebAssembly, them the last two PR's would be really useful for us! Currently, we still have to partially fork the models in Substrate: https://github.com/paritytech/substrate/pull/13031  even so it is really useful that we can overwrite the `msm`'s and only this allows to re-use the algebra test-templates to test the curves with custom host functions in Substrate!

However, I don't know how to do it! We discussed adding `CanonicalSerialize` trait to the `Into<G2Prepared>` arguments, make the arguments `'static` and downcast them with the `any` trait or passing some more explicit arguments (see here: https://github.com/achimcc/algebra/blob/5a515d151d1fda95f487e03f950f56ba7efdcd32/ec/src/models/bls12/g2.rs#L159-L192 for my idea), but none of the ideas were really convincing so far!

**Comment by Pratyush** [comment]
I think it makes sense to add a `CanonicalSerialize + CanonicalDeserialize` bound for the `Into<XPrepared>` arguments: `impl Into<G2Prepared> + CanonicalSerialize + CanonicalDeserialize`

**Comment by achimcc** [comment]
That was my original idea. @burdges had some concerns? Would mean we can serialize without explicitly knowing what we serialize :D I'd probably find a solution for this!

**Comment by burdges** [comment]
We've four-ish  avenues for WASM host calles for pairings:

1. Add non-canonical serialization everywhere, including `G2Prepared`, well `G1Prepared: CanonicalSerialize` already.  This incurs passing 16kb across the boundary twice for a pairing, or once more when reusing `G2Prepared`.  16kb is not much, but it's not nothing either.
2. Add a model with `pub struct G2Prepared<..>(G2Affine<..>);`, make point preperation a non-op, and do a point prepreparation per miller loop.  At first blush this sounds like the worst option, being much slower than 1, but it has a smooth upgrade path into..
3. Add a model with `pub struct G2Prepared<..>(G2Affine<..>);`, make point preparation be a host call that populates a cache, and add another `Drop` host call, so now `G2Affine` acts like a de facto lookup pointer for the host.
4. Actually figure out how Servo does JS/WASM allocations properly from the host, make point preparation allocate WASM memory for `G2Prepared`, and then pass the real pointer around thereafter. 

We should make a similar chart for people wanting to do pairings on GPUs or using other hardware acceleration, as however we change the traits should ideally fit them too.  It's likely but not assured that 1 is good for GPUs but bad for ASICs.

**Comment by achimcc** [comment]
I hope I was not rushing too much with my ideas, but hey, my original PR's where draft PR's to kick off a discussion and got accepted way faster than I expected. I'm also happy to revert those PR's later on if they don't turn out to be the best solution. Given that we are facing a new arkworks release and that I'm conviced that I can avoid forking the models with what we have now if we add the `CanonicalSerialize` trait to the `multi_miller_loop` args, I just created a last PR now for it.

**Comment by burdges** [comment]
Alright, I see why it helps now.  You need some way to do injection into the model.  ASICs and GPUs likely do benefit.  It's also consistent with scalar multiplication handling.  Cool  :)

**Comment by burdges** [comment]
Isn't this done?  We're happy with the ping-pong trick, and likely anyone doing GPUs likes the ping-pong trick too, no?

**Comment by burdges** [comment]
We should figure out if https://github.com/arkworks-rs/algebra/pull/528 and https://github.com/arkworks-rs/algebra/pull/567 should've used the bigint form, ala 
```
    fn msm_bigint(
        bases: &[Affine<Self>],
        bigints: &[<Self::ScalarField as PrimeField>::BigInt],
    ) -> Result<Projective<Self>, usize> {
```
Initially I figured no because [this multi-threaded loop](https://github.com/arkworks-rs/algebra/blob/master/ec/src/scalar_mul/variable_base/mod.rs#L21) but invokes [this Montgomery reduction](https://github.com/arkworks-rs/algebra/blob/master/ff/src/fields/models/fp/montgomery_backend.rs#L372).  I guess this does nothing most of the time though.

I donno the best choice but in principle with https://rust-lang.github.io/impl-trait-initiative/RFCs/rpit-in-traits.html we could've methods vaguely like 
```
pub trait PrimeField: Field {
    ...
    fn iter_bigint_slice(s: &[Self]) -> impl Iterator<Item=Cow<'a,[Self::BigInt]>>;
    ...
}

impl<P: FpConfig<N>, const N: usize> PrimeField for Fp<P, N> {
    ...
    fn iter_bigint_slice<'a>(s: &'a [Self]) -> impl Iterator<Item=Cow<'a,[Self::BigInt]> {
        let moo = |x| if ! x.is_geq_modulus() {
            Cow::Borrowed(&self.0)
        } else {
            Cow::Owned(self.into_bigint())
        };
        s.iter().map(moo)
    }
}
```

**Comment by mmagician** [comment]
Yes I think we can close this by now.

**Comment by burdges** [comment]
We should decide if this should plug in at the `msm_bigint` level though.
