### ISSUE TITLE
Optimize MNT4/6 pairing (2-NAF Miller loop)

### ISSUE THREAD

**Issue by yelhousni** [arkworks-rs/algebra#57]
Currently, MNT4/6 pairing is implemented in projective coordinate with a binary Miller loop. 
Note that the Hamming weight of `ATE_LOOP_COUNT` for both MNT298 and MNT753 is lower when decomposed in 2-NAF. I suggest to implement 2-NAF Miller loop for MNT4 and MNT6.

**Comment by mmagician** [comment]
Closed in https://github.com/arkworks-rs/algebra/pull/445.
