### ISSUE TITLE
Remove bench-templates

### ISSUE THREAD

**Issue by mmaker** [arkworks-rs/algebra#576]
Hi! I was wondering why the crate `bench-template` exists as a separate crate. It's not clear how to run it, and to my knowledge only used inside `curves`. Would it be possible to remove it and integrate it inside `curves`?

**Comment by Pratyush** [comment]
It used to be in `curves`, but I moved it here because it allows us to benchmark `test-curves`.

**Comment by mmaker** [comment]
Speaking of which, the same comment applies ^^" 
Could we move also test-curves inside curves and expose benchmarking and testing templates on enabling a specific feature?

**Comment by Pratyush** [comment]
`test-curves` is in this crate specifically to allow easily testing code in `ff`, `ec`, and `poly` without having to apply a `patch`-based hack, and managing multiple repos.
