### ISSUE TITLE
docs.rs can't build documentation for 0.4

### ISSUE THREAD

**Issue by Pratyush** [arkworks-rs/algebra#587]
See the error log here: https://docs.rs/crate/ark-ff/0.4.0/builds/723044

**Comment by mmaker** [comment]
ouch -- you think this thing is downloading `ark-ff` without the rest of the workspace?

**Comment by Pratyush** [comment]
Yeah, I think it's because the `include` in `Cargo.toml` only includes certain files: https://github.com/arkworks-rs/algebra/blob/master/ff/Cargo.toml#L11
