### ISSUE TITLE
could not find `bls12_381` in `ark_test_curves`

### ISSUE THREAD

**Issue by cryptogakusei** [arkworks-rs/algebra#595]
I am trying to use the ark_test_curves::bls12_381 for my project. However, it seems the cargo gives out an error saying it cannot find the module even though I have specified ark-test-curves = "0.4.0" as a dependency in the toml. Appreciate any help in dealing with this issue. 
<img width="901" alt="Screenshot 2023-02-04 at 9 07 44 AM" src="https://user-images.githubusercontent.com/92956318/216780348-fd83b31d-e942-40e3-8342-2515184ba673.png">

**Comment by mmagician** [comment]
You need to enable the feature "bls12_381_curve": https://github.com/arkworks-rs/algebra/blob/master/test-curves/Cargo.toml#L34

**Comment by mmagician** [comment]
Unless it's for testing purposes, it's recommended to use the curve from the arkworks-rs/curves repo, which will have more optimized operations implemented.

**Comment by cryptogakusei** [comment]
Thanks!
