### ISSUE TITLE
Relaxing the CurveGroup ScalarMul trait bound

### ISSUE THREAD

**Issue by vmx** [arkworks-rs/algebra#596]
I wonder if the `ScalarMul<MulBase = Self::Affine>` trait bound in `CurveGroup`

https://github.com/arkworks-rs/algebra/blob/4e4fc17e69178ab7f929602f17a5e769ebaf34c7/ec/src/lib.rs#L130

could be relaxed to just `ScalarMul<MulBase>`?

Background is that I currently try to implement the arkworks traits for another BLS12-381 implementation. There the MSM operates on the projective points. Currently I'd need to transform them to affine and back to projective.

With this change I could implement `ScalarMul` for the `G1Projective` type and set the `MulBase` associated type 
https://github.com/arkworks-rs/algebra/blob/4e4fc17e69178ab7f929602f17a5e769ebaf34c7/ec/src/scalar_mul/mod.rs#L34-L41
 to `Self`. `VariableBaseMSM::msm()`
https://github.com/arkworks-rs/algebra/blob/4e4fc17e69178ab7f929602f17a5e769ebaf34c7/ec/src/scalar_mul/variable_base/mod.rs#L34
could then be implemented on the projective points without any further conversion.

**Comment by Pratyush** [comment]
Does blstrs accept MSM inputs in projective form?

**Comment by vmx** [comment]
> Does blstrs accept MSM inputs in projective form?

Yes, exactly :)

**Comment by Pratyush** [comment]
Hm that's unfortunate. I'm not sure why they do that, since internally they convert to affine anyway: https://github.com/filecoin-project/blstrs/blob/73d70b91a4808c6dc0d703f5fd605beb8309bf88/src/g1.rs#L638

**Comment by Pratyush** [comment]
I think the way to go would be to call the relevant code from `blst` directly, as is done above.

So the steps I would suggest are to:

1. Make a PR to `blst` to make the `points` field of `Points` `pub`: https://github.com/supranational/blst/blob/146dfa2e67a5cf87ff1e6cc41ea10f51f675a0fd/bindings/rust/src/lib.rs#L1760

2. In your MSM code, construct a `Points` vector from affine elements, and then 

3. Directly invoke `Points::mult` as here: https://github.com/filecoin-project/blstrs/blob/73d70b91a4808c6dc0d703f5fd605beb8309bf88/src/g1.rs#L645

**Comment by vmx** [comment]
> Hm that's unfortunate. I'm not sure why they do that, since internally they convert to affine anyway: https://github.com/filecoin-project/blstrs/blob/73d70b91a4808c6dc0d703f5fd605beb8309bf88/src/g1.rs#L638

Thanks you for having such a close look. I should've really checked that myself. Now it of course totally makes sense to keep the affine transformation and that trait bound.
