### ISSUE TITLE
Rust analyser not inferring input types for ```FixedBase::msm``` and ```VariableBaseMSM::msm```

### ISSUE THREAD

**Issue by Zyouell** [arkworks-rs/algebra#609]
I believe the current definitions of ```VariableBaseMSM::msm``` and ```FixedBase::msm``` may need to be changed.

the method signature for ```FixedBase::msm``` is: 

`pub fn msm<T: ScalarMul>(
        scalar_size: usize,
        window: usize,
        table: &[Vec<<T as ScalarMul>::MulBase>],
        v: &[T::ScalarField],
    ) -> Vec<T>`

I am trying to use this function in a trait with a generic ```E: Pairing ``` in its definition and despite trying many ```where``` clauses Rust can never infer what the type of ```v``` should be. I believe changing the signature to be:

`pub fn msm<T: ScalarMul>(
        scalar_size: usize,
        window: usize,
        table: &[Vec<<T as ScalarMul>::MulBase>],
        v: &[<T as Group>::ScalarField],
    ) -> Vec<T> `
will resolve this issue as it seems like Rust Analyser doesn't know what type to expect. Like wise for the ```VariableBaseMSM``` trait the ```msm``` method signature is:

`fn msm(bases: &[Self::MulBase], scalars: &[Self::ScalarField]) -> Result<Self, usize> `

Changing this to:

`fn msm(bases: &[Self::MulBase], scalars: &[<Self as Group>::ScalarField]) -> Result<Self, usize>`

Should resolve the issue.

**Comment by burdges** [comment]
@achimcc

**Comment by Pratyush** [comment]
Can you post a code snippet of the bug @Zyouell? Thanks!

**Comment by Zyouell** [comment]
@Pratyush the following code causes an error:

```
fn verify_internal<E: Pairing, T: ScalarMul>(
    verifier_param: &MultilinearVerifierParam<E>,
    commitment: &Commitment<E>,
    point: &[E::ScalarField],
    value: &E::ScalarField,
    proof: &MultilinearKzgProof<E>,
) -> Result<bool, PCSError>
where
    E: Pairing<G2 = T>,
{
    let verify_timer = start_timer!(|| "verify");
    let num_var = point.len();

    if num_var > verifier_param.num_vars {
        return Err(PCSError::InvalidParameters(format!(
            "point length ({}) exceeds param limit ({})",
            num_var, verifier_param.num_vars
        )));
    }

    let prepare_inputs_timer = start_timer!(|| "prepare pairing inputs");

    let scalar_size = E::ScalarField::MODULUS_BIT_SIZE as usize;
    let window_size = FixedBase::get_mul_window_size(num_var);

    let h_table =
        FixedBase::get_window_table::<T>(scalar_size, window_size, verifier_param.h.into_group());
    let h_mul: Vec<E::G2> = FixedBase::msm::<T>(scalar_size, window_size, &h_table, point);

    // the first `ignored` G2 parameters are unused
    let ignored = verifier_param.num_vars - num_var;
    let h_vec: Vec<_> = (0..num_var)
        .map(|i| verifier_param.h_mask[ignored + i].into_group() - h_mul[i])
        .collect();
    let h_vec: Vec<E::G2Affine> = E::G2::normalize_batch(&h_vec);
    end_timer!(prepare_inputs_timer);

    let pairing_product_timer = start_timer!(|| "pairing product");

    let mut pairings_1: Vec<_> = proof
        .proofs
        .iter()
        .map(|&x| E::G1Prepared::from(x))
        .collect();

    let mut pairings_2: Vec<_> = h_vec
        .iter()
        .take(num_var)
        .map(E::G2Prepared::from)
        .collect();

    pairings_1.push(E::G1Prepared::from(
        ((verifier_param.g.into_group() * (*value)) - commitment.0.into_group()).into_affine(),
    ));
    pairings_2.push(E::G2Prepared::from(verifier_param.h));

    let res = E::multi_pairing(pairings_1, pairings_2).0 == E::TargetField::one();

    end_timer!(pairing_product_timer);
    end_timer!(verify_timer);
    Ok(res)
}
```

The error occurs on line 28 when I call ` FixedBase::msm `, Rust thinks the variable ` point ` is not of the correct type, Rust analyser  says it expects a variable of type ` &[{unknown}] ` but it found a variable of type ` &[<E as Pairing>::ScalarField] `.

**Comment by Pratyush** [comment]
This is a bug with r-a, not with us
