### ISSUE TITLE
Optimize BW6 Miller loop

### ISSUE THREAD

**Issue by mmagician** [arkworks-rs/algebra#616]
Contrary to the [inline comment](https://github.com/arkworks-rs/algebra/blob/b71caecb0f31f545b8bd7a8062000c7b6d7b190f/ec/src/models/bw6/mod.rs#L58), the Miller loop for BW6 doesn't implement the optimized algorithm that reuses `f_u` in the second loop, and thus allows shortening the second loop.

Reference paper: https://eprint.iacr.org/2020/351.pdf

**Comment by swasilyev** [comment]
Gnark [implements ](https://github.com/ConsenSys/gnark-crypto/blob/8f7ca09273c24ed9465043566906cbecf5dcee91/ecc/bw6-761/pairing.go#L158) an even more sophisticated approach, that is, though, not backwards compatible.
