### ISSUE TITLE
BW6 generic final exponentiation (hard part)

### ISSUE THREAD

**Issue by mmagician** [arkworks-rs/algebra#625]
The current algorithm for computing final exponentiation is specific to BW6-761 following Algorithm 6 from [HG20](https://eprint.iacr.org/2020/351.pdf): https://github.com/arkworks-rs/algebra/blob/6f309fa9bc87434f795f97dc036b302d50bcac7e/ec/src/models/bw6/mod.rs#L189

A generic method is needed in BW6 model that works for all bw6 curves, otherwise new implementations like [the one for BW6-767](https://github.com/arkworks-rs/curves/pull/154) won't work. It would require specifying `h_t` and `h_y` in the model parameters, and then using the generic method as outlined in A.3 from [HG21](https://eprint.iacr.org/2021/1359.pdf).
I've a draft PR though for now the implementation isn't complete: 
https://github.com/arkworks-rs/algebra/pull/624

**Comment by Pratyush** [comment]
Completed in #633
