### ISSUE TITLE
unresolved import `ark_test_curves::ed_on_bls12_381

### ISSUE THREAD

**Issue by bbuenz** [arkworks-rs/algebra#628]
could not find `ed_on_bls12_381` in `ark_test_curves
When running cargo bench
Using
cargo 1.70.0-nightly (4a3c588b1 2023-03-14)

**Comment by kilyig** [comment]
I'm having a similar problem. Currently trying to run the code at [`PrimeField`](https://github.com/arkworks-rs/algebra/tree/master/ff#primefield) in `algebra/ff`, and getting the following error: `error[E0432]: unresolved import 'ark_test_curves::bls12_381'`. Following the suggestion of @Pratyush I added some `[features]` to my `Cargo.toml`. Below is the `Cargo.toml` after adding:
```
[package]
name = "test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-std = "0.4.0"
ark-test-curves = "0.4.2"
num-bigint = "0.4.3"

# from https://github.com/arkworks-rs/algebra/blob/1f7b3c6b215e98fa3130b39d2967f6b43df41e04/test-curves/Cargo.toml#L33
[features]
bls12_381_scalar_field = [] # also tried without this line
bls12_381_curve = [ "bls12_381_scalar_field" ]
```
This configuration gives me the following error:
```
error: failed to parse manifest at `/home/kilyig/Projeler/BCAP/DHPSI/Cargo.toml`

Caused by:
  feature `bls12_381_curve` includes `bls12_381_scalar_field` which is neither a dependency nor another feature
```
I also tried changing the import statement. After typing `use ark_test_curves::`, the closest VS Code suggestion I get is `bls12`. Does anyone know what I should do?

**Comment by mmagician** [comment]
You need:

```
[dependencies]
...
ark-test-curves = { version = "0.4.2", features = ["bls12_381_curve"] }
...
```

Similar to how it's used in ark-ff: https://github.com/arkworks-rs/algebra/blob/6f309fa9bc87434f795f97dc036b302d50bcac7e/ff/Cargo.toml#L31

**Comment by kilyig** [comment]
@mmagician thank you, works now!
