### ISSUE TITLE
CanonicalSerde for Rc and Arc

### ISSUE THREAD

**Issue by alxiong** [arkworks-rs/algebra#649]
1. Currently only `CanonicalSerialize` is implemented for `Rc<T>` [here](https://github.com/arkworks-rs/algebra/blob/master/serialize/src/impls.rs#L292-L306), but the deserialize counterpart is missing.
2. Maybe consider relaxing the feature flag for CanonicalSerde for `Arc<T>` which is [currently only available](https://github.com/arkworks-rs/algebra/blob/master/serialize/src/impls.rs#L308) in `feature="std"`, so I'm hoping:
    - (conditionally) re-export `alloc::sync` under `#[cfg(target_has_atomic = "ptr")]` in `ark-std` as [alloc does it](https://doc.rust-lang.org/alloc/sync/index.html).
    - change the feature directive inside `ark-serialize` to reflect the change.
    - (these changes make it possible to use Arc on platforms that supports atomic ops and pointers, which include MIPS but unfortunately not WASM I believe)

The second request is optional, subject to maintainer's judgement on how relevant or useful will it be to add. But the first point is easy and nice to have.

**Comment by burdges** [comment]
ark-std lags std's alloc in a few ways, like https://github.com/arkworks-rs/std/issues/44  

If rust stabilizes `error_in_core` then ark-std could largely be deprecated.  If someone wants something within the next few years then they should probably update ark-std to a more recent alloc.

**Comment by burdges** [comment]
We might've ark-serialize bugs similar to https://github.com/paritytech/parity-scale-codec/pull/426 but maybe less easy to solve.  I suppose serde could've much worse similar bugs.
