### ISSUE TITLE
How to transfer data structure from other lib to ark

### ISSUE THREAD

**Issue by shenrn1998** [arkworks-rs/algebra#657]
Hi there!

I would like to use both ark-ec and other ZKP library in my project. The current problem is that I am not sure how to transfer data structure from other lib to ark-ec one's. I have checked the tutorial and found that something like "bls12_381::G1Projective::rand()" can be used to generate new random points. But I hope to have my points assigned. For instance, assign one point like (XXX, YYY) into the ark form. Also, I need to perform MSM, so I hope to learn how to assign scalars either.

Thanks a lot!

**Comment by Pratyush** [comment]
You can use [`bls12_381::G1Affine::new`](https://docs.rs/ark-ec/latest/ark_ec/models/short_weierstrass/struct.Affine.html) method
