### ISSUE TITLE
`ark_std::Zero` should be `ark_group::Zero`?

### ISSUE THREAD

**Issue by mmaker** [arkworks-rs/algebra#670]
Right now `Zero` is in ark_std but perhaps it'd be better fit next to the definition of `AdditiveGroup`?

**Comment by slumber** [comment]
`Zero` is just a re-export from `num-traits`, implemented not only for groups, but for example for fields in ark_ff.

**Comment by mmaker** [comment]
`ark_ff` depends on `ark_group` for additive groups

**Comment by Pratyush** [comment]
We can re-export it from ark-group too
