### ISSUE TITLE
Derive macro `MontConfig` panics if any other attribute is applied

### ISSUE THREAD

**Issue by aleasims** [arkworks-rs/algebra#704]
When I'm trying to apply any additional attributes to structure with `#[derive(MontConfig)]`, it results in a panic:

```
error: proc-macro derive panicked
 --> /root/proj/arkworks-curves/pallas/src/fields/fq.rs:4:10
  |
4 | #[derive(MontConfig)]
  |          ^^^^^^^^^^
  |
  = help: message: attribute modulus should be a string
```

E.g in case I want my config structure depend on some feature, I can't compile something like:

```rust
#[derive(MontConfig)]
#[modulus = "28948022309329048855892746252171976963363056481941560715954676764349967630337"]
#[generator = "5"]
#[cfg(feature = "some_feature_name")]
pub struct FqConfig;
```

As far as I understood, the problem is in `ark_ff_macros::fetch_attr` function, which rejects any meta except `syn::Meta::NameValue`. That's why attribute `#[cfg(feature = "some_feature_name")]` leads to a panic.

Is there any reason, why you disallow other attributes for `MontConfig` structures?

**Comment by mmagician** [comment]
You're right, this is a potentially desirable feature. I'm not aware of any way of doing directly what you're proposing. 
I can offer a simple workaround though:

```
#[cfg(feature = "feature1")]
pub use fp::FqConfig;

#[cfg(feature = "feautre1")]
mod fp {
    use ark_ff::fields::{Fp384, MontBackend, MontConfig};

    #[derive(MontConfig)]
    #[modulus = "28948022309329048855892746252171976963363056481941560715954676764349967630337"]
    #[generator = "5"]
    pub struct FqConfig;
}

#[cfg(feature = "feature2")]
pub use fp::{Fq, FqConfig};

#[cfg(feature = "feature2")]
mod fp {...}
```

I hope this helps!

**Comment by aleasims** [comment]
@mmagician Thanks for your answer!

I've come up with a possible fix for this issue, including changes in `ark-ff-macros`. Hope that will close this issue.

- #747
