### ISSUE TITLE
Implement `core::ops::Shr for BigInt` in place of `BigInt::divn()`

### ISSUE THREAD

**Issue by mmaker** [arkworks-rs/algebra#714]
https://github.com/arkworks-rs/algebra/blob/master/ff/src/biginteger/mod.rs#L434 
The BigInt::divn function should instead be done with overloading using the trait Shr from the standard library. 
(Cf. #713)

**Comment by mmaker** [comment]
@hdvanegasm want to give it a shot? :)

**Comment by hdvanegasm** [comment]
I would like to implement not only `core::ops::Shr` but also `core::ops::Shl`. If I will implement `core::ops::Shl` for `BigInt<N>` by moving it `M` bits, should I return a `BigInt<N + M>` or should I just return a BigInt<N> and chopping the overflow?

**Comment by mmaker** [comment]
This issue is just for `Shr` :)
