### ISSUE TITLE
TWO_ADICITY check in Radix2EvaluationDomain for BW6-767

### ISSUE THREAD

**Issue by mskrzypkows** [arkworks-rs/algebra#799]
I'd like to use the BW6-767 curve for a proof that has an inner proof based on BLS12-381. As I'm doing so, I receive an error: `Error: polynomial degree is too large`. I've done some debugging with arkworks and found out that this check is a source of an error: https://github.com/arkworks-rs/algebra/blob/master/poly/src/domain/radix2/mod.rs#L63
`F::TWO_ADICITY` is equal to one for BW6-767: https://github.com/arkworks-rs/algebra/blob/master/curves/bw6_767/src/fields/fq3.rs#L20

Is this desired behaviour? It seems to be odd that `log_size_of_group` should be at most 1.

I've created an example that shows the problem: https://github.com/mskrzypkows/arkworks_recursive_proof/blob/main/src/main.rs

**Comment by mmagician** [comment]
It's not the log of size of the group, see [here](https://github.com/arkworks-rs/algebra/blob/77efd9892de9ef40b480b9ac5d327706bc56195d/ff/src/fields/fft_friendly.rs#L9)

Value of 1 is correct, see [this document](https://hackmd.io/@gnark/bw6_bls12381#2-chains) for more info.

To confirm, you can run the following in `sage`:
```
$ # subgroup order of BLS12-381
$ r = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001
$ sage: valuation(r - 1, 2)
$ 32
$ # subgroup order of BW6-767
$ r = 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab
$ sage: valuation(r - 1, 2)
# 1
```

**Comment by mmagician** [comment]
So you cannot do meaningful radix-2 FFT with BW6-767. I think @swasilyev did some work on mixed radix for BW6-767 specifically, but not sure how far this work is.

Otherwise you'd need to do naive interpolation/eval.

**Comment by mskrzypkows** [comment]
OK, thanks for the answer. I see that mixed radix isn't ready for BW6-767 yet, e.g. this will not let choosing domain size: https://github.com/arkworks-rs/algebra/blob/master/poly/src/domain/mixed_radix.rs#L260

**Comment by mskrzypkows** [comment]
> Otherwise you'd need to do naive interpolation/eval.

I see that by default `GeneralEvaluationDomain` is used, which uses `FftField`. 
https://github.com/arkworks-rs/groth16/blob/master/src/generator.rs#L89
So, if I want to use native evaluation I need a different type of evaluation domain (not using `FftField`), right? 
Or add native evaluation to the `GeneralEvaluationDomain`?

**Comment by swasilyev** [comment]
You'll have to implement EvaluationDomain yourself. Here is a prototype implementing DFTs for some subgroup sizes of BLS12-381 using Cooley–Tukey FFT and Rader's transform.https://github.com/w3f/ring-proof/compare/master...smooth-fft
