### ISSUE TITLE
Final exponentiation in BLS12-381not producing `(p ^ k - 1) / r`

### ISSUE THREAD

**Issue by NikolayKostadinov21** [arkworks-rs/algebra#814]
### Description
The algorithms used in the final exponentiation of BLS12-381 are based on this [paper](https://eprint.iacr.org/2020/875.pdf). [The final exponentiation](https://eprint.iacr.org/2020/875.pdf#page=6) is just exponentiation by a fixed large exponent `(p^k - 1) / r` where p is the field modulus, r is the subgroup size and k is the embedding degree and their [respective values](https://hackmd.io/@benjaminion/bls12-381#Curve-equation-and-parameters) (for BLS12-381) are: 
`p: 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab`
`r: 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001`
`k: 12`. It must be performed to obtain an element of `Gt` of order `r` to ensure output uniqueness, algorithmic correctness, and security for pairing-based cryptography.
### Observation
The following test fails:
```
    #[test]
    fn test_ark_final_exponentiation() {
        use ark_bls12_381::{Fq, Fq12, Fr};
        use ark_ff::{Field, UniformRand};
        use num::BigUint;
        let rng = &mut rand::thread_rng();
        let rand_x = Fq12::rand(rng);
        let ark_final_exponentiation =
            ark_bls12_381::Bls12_381::final_exponentiation(MillerLoopOutput(rand_x))
                .unwrap()
                .0;

        use ark_ff::PrimeField;
        let p: BigUint = Fq::MODULUS.into();
        let r: BigUint = Fr::MODULUS.into();
        let exponent = (p.pow(12) - 1u32) / r;
        let fixed_large_exponent = rand_x.pow(&exponent.to_u64_digits());
        
        // Fails
        assert_eq!(ark_final_exponentiation, fixed_large_exponent);
    }
  ```
Since the fixed large exponent `(p ^ k − 1) / r` of final exponentiation is broken down into two parts(easy part and hard part) we can individually test the easy and hard part in isolation thus concentrating on a smaller area where the problem may be. I performed test where I am testing the easy part in isolation and I found out that the easy part is just fine.
```
    #[test]
    fn test_ark_easy_part() {
        use ark_bls12_381::{Fq, Fq12};
        use ark_ff::{Field, UniformRand};
        use num::BigUint;
        let rng = &mut rand::thread_rng();
        let rand_x = Fq12::rand(rng);
        let ark_easy_part = ark_easy_part(rand_x).unwrap();

        // f_easy = x^((p^6 - 1)*(p^2 + 1))
        use ark_ff::PrimeField;
        let p: BigUint = Fq::MODULUS.into();
        let exponent = (p.pow(6) - 1u32) * (p.pow(2) + 1u32);
        let fixed_large_exponent = rand_x.pow(&exponent.to_u64_digits());

        // Passes
        assert_eq!(ark_easy_part, fixed_large_exponent);
    }
```
However I cannot say the same thing for the hard part as the test below fails:
```
    #[test]
    fn test_ark_hard_part() {
        use ark_bls12_381::{Fq, Fq12};
        use ark_ff::UniformRand;
        use num::BigUint;
        let rng = &mut rand::thread_rng();
        let rand_x = Fq12::rand(rng);
        let ark_hard_part = hard_part_native(rand_x);

        // (p^12 - 1) / r = f_easy * ((p^4 - p^2 + 1) / r)
        use ark_ff::PrimeField;
        let p: BigUint = Fq::MODULUS.into();
        let r: BigUint = Fr::MODULUS.into();

        let fixed_large_exponent = (p.pow(12) - 1u32) / r.clone();
        let easy_part = (p.pow(6) - 1u32) * (p.pow(2) + 1u32);
        let hard_part = (p.pow(4) - p.pow(2) + 1u64) / r;
        let expected_hard_part = fixed_large_exponent.clone() / easy_part.clone();
        let expected_final_exponentiation = hard_part.clone() * easy_part;

        // Passes
        assert_eq!(expected_final_exponentiation, fixed_large_exponent);

        // Passes
        assert_eq!(expected_hard_part, hard_part);

        // Fails
        let expected_result = rand_x.pow(&hard_part.to_u64_digits());
        assert_eq!(ark_hard_part, expected_result);
    }
```
This is a clear indication that the problems is in the hard part of the final exponentiation. The helper functions `ark_easy_part` and `hard_part_native` that I am using are following the library's implementation.

**Comment by Pratyush** [comment]
Thank you for raising this question! 
As per the top of page 14 of https://eprint.iacr.org/2020/875.pdf#page=14, we actually compute `3 * (p^12 - 1)/r`. This is sufficient for the pairing: essentially we're computing pairing_result^3, which is still fine, as cubing cannot take us outside the r-order subgroup of Fp12^*.
