### ISSUE TITLE
Make FFTs nlog(d)

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/algebra#83]
FFTs in the library are all nlog(n). However they could be nlog(d), which is an efficiency improvement when doing polynomial multiplication. 

This can be taken advantage of in two possible ways:
* Split up the FFT into n/d independent FFTs operating over the same polynomial, but evaluating on distinct cosets. Both of these sub-FFTs are dlog(d). At the end concatenate these two vectors.
* Skip the first few rounds of butterflying / arithmetic in the current FFT algorithm, and just copy the polynomial coefficients into the correct positions. This is implemented in libiop.

This probably doesn't matter for the current pairing based SNARKs as they are dominated by MSM time.

**Comment by Pratyush** [comment]
This would help any time we do a polynomial multiplication, since the domain is necessarily equal to the sum of the degrees of the involved polynomial, and is hence usually at least double their degree.

**Comment by Pratyush** [comment]
@andrewmilson this change becomes possible with your work in #487; if you would like to take a stab at implementing the first approach @ValarDragon mentioned, that would be fantastic!

**Comment by andrewmilson** [comment]
Thanks @Pratyush. Yeah keen to take a stab!

**Comment by Pratyush** [comment]
Awesome! Let me know if you have any questions about the approach; you can ask here or on Discord.

**Comment by andrewmilson** [comment]
@Pratyush unless I'm missing something I think it might be easier going straight to the second approach @ValarDragon mentioned. 

With the first approach It's easy to obtain the values for the smaller FFTs evaluated on the coset domains but transposing the values so they are in order is not so easy. I haven't spent too much time looking into it but I don't think it's trivial to do without allocating extra memory.

**Comment by Pratyush** [comment]
You're right that the shuffles to put things in place are somewhat non-trivial, and might cause bad non-locality. It would be good to check what the situation would be like for the other approach.

Re: extra memory, we will need to allocate extra memory either way, since the output (evaluations) is larger than the input (polynomial)

**Comment by andrewmilson** [comment]
With the first approach I mean additional memory on top of resizing the coefficients to the size of the domain.

The second approach has better locality and no need to allocate more memory than necessary. I put together a quick draft PR #493 just for ideas. I know you mentioned above you are "intending to refactor the FFT infrastructure". I'd be keen to hear what your thoughts are here. I'm more than happy to take the implementation further, just let me know.
