### ISSUE TITLE
Deserialization of array can panic

### ISSUE THREAD

**Issue by ggwpez** [arkworks-rs/algebra#834]
The deserialisation code of a static sized array uses `unwrap` instead of propagating the error:  

https://github.com/arkworks-rs/algebra/blob/065cd24fc5ae17e024c892cee126ad3bd885f01c/serialize/src/impls.rs#L481-L483

This was possibly done since the `try_from_fn` function is experimental. However, it can cause a panic instead of an error return.

I would propose to use a vector with capacity. There is probably a way to make it a faster with `unsafe`, but thats not my speciality:

```rust
let mut result = Vec::<T>::with_capacity(N);
for i in 0 .. N {
    result.push(T::deserialize_with_mode(&mut reader, compress, validate)?);
}

let array: [T; N] = result.try_into().map_err(|_| SerializationError::InvalidData)?;
Ok(array)
```

**Comment by burdges** [comment]
Yeah, this is a serious bug.  nice catch.

There are crates that do this, like [arrayvec](https://docs.rs/arrayvec/latest/arrayvec/struct.ArrayVec.html), but the unsafe solution looks like this:
```
impl<T: CanonicalDeserialize, const N: usize> CanonicalDeserialize for [T; N] {
    #[inline]
    fn deserialize_with_mode<R: Read>(
        mut reader: R,
        compress: Compress,
        validate: Validate,
    ) -> Result<Self, SerializationError> {
        let mut array = MaybeUninit::uninit_array::<N>();
        for i in 0..N {
            array[i].write(T::deserialize_with_mode(&mut reader, compress, Validate::No) ?);
        }
        if let Validate::Yes = validate {
            T::batch_check(result.iter())?
        }
        Ok(unsafe { MaybeUninit::array_assume_init(array) })
    }
}
```
What this unsafe is solving is the possibility that no sensible default initilization exists for `T`.

**Comment by Pratyush** [comment]
We want to avoid allocation when possible, but the `MaybeUninit` solution looks reasonable to me. Would folks be interested in opening a PR?

**Comment by burdges** [comment]
Appears arrayvec already gets used in ff, so maybe that isolated the unsafety better.
```
impl<T: CanonicalDeserialize, const N: usize> CanonicalDeserialize for [T; N] {
    #[inline]
    fn deserialize_with_mode<R: Read>(
        mut reader: R,
        compress: Compress,
        validate: Validate,
    ) -> Result<Self, SerializationError> {
        let mut array = ArrayVec::<T, N>::new();
        for i in 0..N {
            array[i].write(T::deserialize_with_mode(&mut reader, compress, Validate::No) ?);
        }
        if let Validate::Yes = validate {
            T::batch_check(result.iter())?
        }
        Ok(array.into_inner())
    }
}
```
