### ISSUE TITLE
Change evaluation domain API for cosets

### ISSUE THREAD

**Issue by ValarDragon** [arkworks-rs/algebra#88]
Could the struct for an evaluation domain contain a Field element for the affine shift, which then enables it for use as any coset. This not existing required me to re-implement a subset of this logic. (The current API only supports cosets with shift `g`, for a subset of methods)

My suggested API:
* Have two constructors, one for the subgroup case, one for the coset case.
* Remove cosetFFT, instead have the FFTs switch "if affine_shift == Field::one()"
* Add coset support in the lagrange interpolations. This is simple to do (see libiop: https://github.com/alexchmit/libiop-dev/blob/master/libiop/algebra/lagrange.tcc#L177. I also suggest switching to its method of doing arithmetic as it avoids doing one more pass over the array, with the same number of arithmetic ops)
* Update the vanishing polynomial, this just requires setting the constant term to `affine_offset^|H|`

**Comment by ValarDragon** [comment]
Had a discussion with @Pratyush regarding an API for this.

1) Make Domain have two constructors, `new_subgroup(subgroup_size)` and `new_coset(coset_size, offset)`. 
2) Remove cosetFFT / cosetIFFT methods
3) Add a convenience method `domain.get_coset(offset)`, to make it easy to go from subgroup -> coset.

**Comment by andrewmilson** [comment]
Are these changes still wanted? If so I'm happy to submit a pull request for this

**Comment by Pratyush** [comment]
Yes!
