### ISSUE TITLE
Too liberal bool deserialize?

### ISSUE THREAD

**Issue by jon-chuang** [arkworks-rs/algebra#95]
This is the current deserialize for bool:
`Ok(u8::deserialize(reader)? == 1)`

However, this is not necessarily the behaviour we want. In fact, I think we should error if the result is not in `{0, 1}`, which I think might have been the old behaviour.

**Comment by ValarDragon** [comment]
I'm in favor of ensuring that its in `{0,1}` (and in general making encodings unique)
